"""add race tables

Revision ID: 012_add_race_tables
Revises: 011_align_id_types
Create Date: 2026-02-27 14:47:48.965138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '012_add_race_tables'
down_revision: Union[str, None] = '011_align_id_types'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('races',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_aliases', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race_editions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=16), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'year', name='uq_race_edition_year')
    )
    op.create_table('race_distances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('elevation_gain_m', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edition_id'], ['race_editions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edition_id', 'name', name='uq_race_distance_name')
    )
    op.create_table('race_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('distance_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('time_seconds', sa.Integer(), nullable=False),
    sa.Column('place', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.String(length=4), nullable=True),
    sa.Column('club', sa.String(length=255), nullable=True),
    sa.Column('bib', sa.String(length=16), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(length=8), nullable=True),
    sa.Column('over_time_limit', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['distance_id'], ['race_distances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_race_results_distance_id', 'race_results', ['distance_id'], unique=False)
    op.create_index('ix_race_results_name', 'race_results', ['name'], unique=False)
    op.create_table('user_race_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('race_result_id', sa.Integer(), nullable=False),
    sa.Column('matched_by', sa.String(length=16), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['race_result_id'], ['race_results.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'race_result_id', name='uq_user_race_result')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_race_results')
    op.drop_index('ix_race_results_name', table_name='race_results')
    op.drop_index('ix_race_results_distance_id', table_name='race_results')
    op.drop_table('race_results')
    op.drop_table('race_distances')
    op.drop_table('race_editions')
    op.drop_table('races')
    # ### end Alembic commands ###
